id: ID7033B8E
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:08:46.898529
last_modified: 2023-02-09 15:08:46.898649
source_metadata:
  title: 'MSV 1,11: Pāṇḍulohitakavastu'
  language: sa
bases:
  E972:
    base_file: E972.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
